// js/testData.js
//
// Firestore 없이도 지도/필터/마커/리스트를 바로 테스트할 수 있도록 만든
// 하드코딩 테스트 데이터입니다 (요구사항 29).
// 실제 Google/Naver Places API를 호출하지 않고 직접 작성한 예시 데이터입니다.
//
// 이 파일은 scripts/seed-firestore.html 에서도 그대로 재사용되어
// Firestore의 restaurants 컬렉션을 채우는 시드 데이터로도 쓰입니다.

export const TEST_RESTAURANTS = [
  {
    id: "restaurant001",
    name: "스시 사카바 사시스",
    country: "JP",
    region: "Osaka",
    district: "Umeda",
    latitude: 34.7024,
    longitude: 135.4959,
    categories: ["sushi", "japanese"],
    status: "want",
    external: {
      provider: "google",
      name: "Sushi Sakaba Sashisu",
      rating: 4.6,
      ratingCount: 1284,
      url: "https://maps.google.com/?q=Sushi+Sakaba+Sashisu+Osaka",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "웨이팅이 길지만 가볼 가치 있음" },
    openingHours: ["11:30-22:00"],
    address: "大阪府大阪市北区角田町...",
    phone: "",
  },
  {
    id: "restaurant002",
    name: "이치ran 라멘 도톤보리점",
    country: "JP",
    region: "Osaka",
    district: "Dotonbori",
    latitude: 34.6687,
    longitude: 135.5013,
    categories: ["ramen"],
    status: "visited",
    external: {
      provider: "google",
      name: "Ichiran Ramen Dotonbori",
      rating: 4.3,
      ratingCount: 8452,
      url: "https://maps.google.com/?q=Ichiran+Dotonbori",
    },
    my: { ratingSum: 4.0, ratingCount: 1, memo: "1인 칸막이석. 진한 돈코츠 국물." },
    openingHours: ["10:00-23:00"],
    address: "大阪府大阪市中央区道頓堀...",
    phone: "",
  },
  {
    id: "restaurant003",
    name: "규카츠 모토무라 신사이바시",
    country: "JP",
    region: "Osaka",
    district: "Shinsaibashi",
    latitude: 34.6731,
    longitude: 135.5013,
    categories: ["yakiniku", "japanese"],
    status: "want",
    external: {
      provider: "google",
      name: "Gyukatsu Motomura",
      rating: 4.4,
      ratingCount: 3021,
      url: "https://maps.google.com/?q=Gyukatsu+Motomura+Shinsaibashi",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "" },
    openingHours: ["11:00-22:30"],
    address: "大阪府大阪市中央区心斎橋筋...",
    phone: "",
  },
  {
    id: "restaurant004",
    name: "긴자 텐동 텐도쿠니",
    country: "JP",
    region: "Tokyo",
    district: "Ginza",
    latitude: 35.6717,
    longitude: 139.7639,
    categories: ["japanese", "curry"],
    status: "visited",
    external: {
      provider: "google",
      name: "Tendon Tenkuni Ginza",
      rating: 4.2,
      ratingCount: 612,
      url: "https://maps.google.com/?q=Tendon+Tenkuni+Ginza",
    },
    my: { ratingSum: 4.5, ratingCount: 1, memo: "튀김옷이 얇고 바삭함. 가성비 좋음." },
    openingHours: ["11:00-21:00"],
    address: "東京都中央区銀座...",
    phone: "",
  },
  {
    id: "restaurant005",
    name: "시부야 카페 라이트하우스",
    country: "JP",
    region: "Tokyo",
    district: "Shibuya",
    latitude: 35.6595,
    longitude: 139.7005,
    categories: ["cafe", "dessert"],
    status: "want",
    external: {
      provider: "google",
      name: "Cafe Lighthouse Shibuya",
      rating: 4.5,
      ratingCount: 421,
      url: "https://maps.google.com/?q=Cafe+Lighthouse+Shibuya",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "핸드드립 커피 유명" },
    openingHours: ["09:00-19:00"],
    address: "東京都渋谷区...",
    phone: "",
  },
  {
    id: "restaurant006",
    name: "성수 곱창이야기",
    country: "KR",
    region: "Seoul",
    district: "Seongsu",
    latitude: 37.5446,
    longitude: 127.0559,
    categories: ["korean", "yakiniku"],
    status: "visited",
    external: {
      provider: "naver",
      name: "성수 곱창이야기",
      rating: 4.4,
      ratingCount: 2033,
      url: "https://map.naver.com/p/search/성수%20곱창이야기",
    },
    my: { ratingSum: 4.5, ratingCount: 1, memo: "곱창 두툼하고 냄새 없음. 웨이팅 30분+" },
    openingHours: ["16:00-24:00"],
    address: "서울특별시 성동구 성수동...",
    phone: "",
  },
  {
    id: "restaurant007",
    name: "을지로 골뱅이무침 노포",
    country: "KR",
    region: "Seoul",
    district: "Euljiro",
    latitude: 37.5663,
    longitude: 126.9910,
    categories: ["korean", "izakaya"],
    status: "want",
    external: {
      provider: "naver",
      name: "을지로 골뱅이무침 노포",
      rating: 4.1,
      ratingCount: 890,
      url: "https://map.naver.com/p/search/을지로%20골뱅이무침",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "노가리+골뱅이무침 조합 유명" },
    openingHours: ["17:00-01:00"],
    address: "서울특별시 중구 을지로...",
    phone: "",
  },
  {
    id: "restaurant008",
    name: "합정 오마카세 스시덴",
    country: "KR",
    region: "Seoul",
    district: "Hapjeong",
    latitude: 37.5498,
    longitude: 126.9139,
    categories: ["sushi"],
    status: "avoid",
    external: {
      provider: "naver",
      name: "합정 오마카세 스시덴",
      rating: 3.8,
      ratingCount: 145,
      url: "https://map.naver.com/p/search/합정%20오마카세%20스시덴",
    },
    my: { ratingSum: 2.0, ratingCount: 1, memo: "가격 대비 재료 신선도 아쉬움. 재방문 X" },
    openingHours: ["18:00-23:00"],
    address: "서울특별시 마포구 합정동...",
    phone: "",
  },
  {
    id: "restaurant009",
    name: "해운대 밀면집",
    country: "KR",
    region: "Busan",
    district: "Haeundae",
    latitude: 35.1587,
    longitude: 129.1604,
    categories: ["korean"],
    status: "visited",
    external: {
      provider: "naver",
      name: "해운대 밀면집",
      rating: 4.3,
      ratingCount: 1502,
      url: "https://map.naver.com/p/search/해운대%20밀면집",
    },
    my: { ratingSum: 4.0, ratingCount: 1, memo: "여름에 특히 좋음. 만두도 맛있음" },
    openingHours: ["10:30-21:00"],
    address: "부산광역시 해운대구...",
    phone: "",
  },
  {
    id: "restaurant010",
    name: "남포동 씨앗호떡",
    country: "KR",
    region: "Busan",
    district: "Nampo",
    latitude: 35.0977,
    longitude: 129.0303,
    categories: ["dessert", "korean"],
    status: "want",
    external: {
      provider: "naver",
      name: "남포동 씨앗호떡",
      rating: 4.5,
      ratingCount: 3311,
      url: "https://map.naver.com/p/search/남포동%20씨앗호떡",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "" },
    openingHours: ["11:00-22:00"],
    address: "부산광역시 중구 남포동...",
    phone: "",
  },
  {
    id: "restaurant011",
    name: "교토 니시키 이자카야",
    country: "JP",
    region: "Kyoto",
    district: "Nishiki",
    latitude: 35.0051,
    longitude: 135.7649,
    categories: ["izakaya", "japanese"],
    status: "want",
    external: {
      provider: "google",
      name: "Nishiki Izakaya Kyoto",
      rating: 4.4,
      ratingCount: 733,
      url: "https://maps.google.com/?q=Nishiki+Izakaya+Kyoto",
    },
    my: { ratingSum: 0, ratingCount: 0, memo: "니시키 시장 근처, 제철 안주 위주" },
    openingHours: ["17:00-24:00"],
    address: "京都府京都市中京区...",
    phone: "",
  },
  {
    id: "restaurant012",
    name: "하카타 라멘 잇푸도 본점",
    country: "JP",
    region: "Fukuoka",
    district: "Hakata",
    latitude: 33.5936,
    longitude: 130.4017,
    categories: ["ramen"],
    status: "visited",
    external: {
      provider: "google",
      name: "Ippudo Ramen Hakata Honten",
      rating: 4.3,
      ratingCount: 5210,
      url: "https://maps.google.com/?q=Ippudo+Hakata+Honten",
    },
    my: { ratingSum: 4.5, ratingCount: 1, memo: "돈코츠의 원조. 사리 추가 무료" },
    openingHours: ["11:00-23:00"],
    address: "福岡県福岡市博多区...",
    phone: "",
  },
];
